@ECHO OFF
REM REG ADD HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced /V ShowSecondsInSystemClock /D 1 /T REG_DWORD /F
REM TASKKILL /IM EXPLORER.EXE /F /T
REM PAUSE
REM EXPLORER.EXE
GOTO S

:S
CLS
ECHO %DATE%%TIME%
SLEEP.EXE 944
GOTO S