set_property SRC_FILE_INFO {cfile:D:/Xilinx/Vivado/projects/project_4/project_4.srcs/constrs_1/new/xdc.xdc rfile:../../../project_4.srcs/constrs_1/new/xdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports led]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports clk]
