# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# XDC: new/bt_uart_EGo1.xdc

# IP: ip/char_fifo/char_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==char_fifo || ORIG_REF_NAME==char_fifo} -quiet] -quiet
