set_property IOSTANDARD LVCMOS33 [get_ports {n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {n[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {result[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[11]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN P5 [get_ports rst]
set_property PACKAGE_PIN P17 [get_ports clk]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]

set_property PACKAGE_PIN K2 [get_ports {result[0]}]
set_property PACKAGE_PIN J2 [get_ports {result[1]}]
set_property PACKAGE_PIN J3 [get_ports {result[2]}]
set_property PACKAGE_PIN H4 [get_ports {result[3]}]
set_property PACKAGE_PIN J4 [get_ports {result[4]}]
set_property PACKAGE_PIN G3 [get_ports {result[5]}]
set_property PACKAGE_PIN G4 [get_ports {result[6]}]
set_property PACKAGE_PIN F6 [get_ports {result[7]}]
set_property PACKAGE_PIN K3 [get_ports {result[8]}]
set_property PACKAGE_PIN M1 [get_ports {result[9]}]
set_property PACKAGE_PIN L1 [get_ports {result[10]}]
set_property PACKAGE_PIN K6 [get_ports {result[11]}]

set_property PACKAGE_PIN R1 [get_ports {n[0]}]
set_property PACKAGE_PIN N4 [get_ports {n[1]}]
set_property PACKAGE_PIN M4 [get_ports {n[2]}]
set_property PACKAGE_PIN R2 [get_ports {n[3]}]

set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS33} [get_ports s]

set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {an[7]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {an[6]}]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports {an[5]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {an[4]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {an[3]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports {an[2]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {an[1]}]
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {an[0]}]

set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports {a_to_g_0[6]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports {a_to_g_0[5]}]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports {a_to_g_0[4]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {a_to_g_0[3]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {a_to_g_0[2]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {a_to_g_0[1]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {a_to_g_0[0]}]

set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {a_to_g_1[6]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {a_to_g_1[5]}]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {a_to_g_1[4]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {a_to_g_1[3]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports {a_to_g_1[2]}]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports {a_to_g_1[1]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {a_to_g_1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property PACKAGE_PIN K1 [get_ports led]
